services:
    app-db:
        image: postgres:17
        volumes:
            - app_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: webld
            POSTGRES_USER: webld
            POSTGRES_PASSWORD: kais12345
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"

volumes:
    app_db_data:
