// Generated by accept-md. Do not edit the markdown block by hand.
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

import { getMarkdownForPath, loadConfig } from "accept-md-runtime";

import { getRequestBaseUrl, isPathExcluded, resolveRequestPath } from "@/utils/request-utils";
import { withErrorHandler } from "@/utils/with-error-handler";

const cache = new Map();
const HANDLER_PATH = "/api/accept-md";
const EXCLUDED_PATH_PREFIXES = ["/api/", "/_next/"] as const;
const NOT_FOUND_MARKDOWN = "# 404 Not Found\n\nThe requested page could not be found.\n";

const getFetchErrorStatusCode = (error: unknown) => {
	if (!(error instanceof Error)) {
		return null;
	}

	const statusMatch = error.message.match(/Failed to fetch page:\s*(\d{3})/);
	if (!statusMatch) {
		return null;
	}

	const statusCode = Number.parseInt(statusMatch[1], 10);
	if (!Number.isFinite(statusCode) || statusCode < 400 || statusCode > 599) {
		return null;
	}

	return statusCode;
};

export const GET = withErrorHandler(async (request: NextRequest) => {
	const path = resolveRequestPath(request, {
		pathHeaderName: "x-accept-md-path",
		queryParamName: "path",
		handlerPath: HANDLER_PATH,
	});

	if (isPathExcluded(path, EXCLUDED_PATH_PREFIXES)) {
		return NextResponse.json({ error: "Not found" }, { status: 404 });
	}

	const config = loadConfig(process.cwd());

	const headers = new Headers(request.headers);
	headers.delete("accept");

	try {
		const markdown = await getMarkdownForPath({
			pathname: path,
			baseUrl: config.baseUrl ?? getRequestBaseUrl(request),
			config,
			cache: config.cache !== false ? cache : undefined,
			headers,
		});
		return new NextResponse(markdown, {
			headers: {
				"Content-Type": "text/markdown; charset=utf-8",
				"Cache-Control": config.cache ? "public, s-maxage=60, stale-while-revalidate" : "no-store",
			},
		});
	} catch (err) {
		const statusCode = getFetchErrorStatusCode(err);
		if (statusCode === 404) {
			return new NextResponse(NOT_FOUND_MARKDOWN, {
				status: 404,
				headers: {
					"Content-Type": "text/markdown; charset=utf-8",
					"Cache-Control": "no-store",
				},
			});
		}

		return NextResponse.json(
			{ error: err instanceof Error ? err.message : "Markdown generation failed" },
			{ status: 500 }
		);
	}
});
