// Generated by accept-md. Do not edit the markdown block by hand.
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

import { getMarkdownForPath, loadConfig } from "accept-md-runtime";

import { isPathExcluded, resolveRequestPath } from "@/utils/request-utils";
import { withErrorHandler } from "@/utils/with-error-handler";

const cache = new Map();
const HANDLER_PATH = "/api/accept-md";
const EXCLUDED_PATH_PREFIXES = ["/api/", "/_next/"] as const;
const NOT_FOUND_MARKDOWN = "# 404 Not Found\n\nThe requested page could not be found.\n";

type BaseURLRequest = {
	headers: {
		get: (name: string) => string | null;
	};
	nextUrl?: {
		protocol: string;
		origin: string;
	};
};

const firstNonEmpty = (...values: Array<string | null | undefined>) => {
	for (const value of values) {
		if (typeof value === "string" && value.trim() !== "") {
			return value;
		}
	}

	return null;
};

const getFirstHeaderValue = (request: BaseURLRequest, headerName: string) => {
	const value = request.headers.get(headerName);
	if (!value || value.trim() === "") {
		return null;
	}

	return (
		value
			.split(",")
			.map((part) => part.trim())
			.find((part) => part.length > 0) ?? null
	);
};

const getBaseURLFromRequest = (request: BaseURLRequest, fallbackPort: number | string) => {
	const forwardedHost = getFirstHeaderValue(request, "x-forwarded-host");
	const host = getFirstHeaderValue(request, "host");
	const resolvedHost = firstNonEmpty(forwardedHost, host);

	if (resolvedHost) {
		const forwardedProto = getFirstHeaderValue(request, "x-forwarded-proto");
		const protocolFromUrl = request.nextUrl?.protocol.replace(/:$/, "");
		const protocol = firstNonEmpty(forwardedProto, protocolFromUrl) ?? "https";

		return new URL(`${protocol}://${resolvedHost}`);
	}

	return request.nextUrl?.origin ? new URL(request.nextUrl.origin) : new URL(`http://localhost:${fallbackPort}`);
};

export const GET = withErrorHandler(async (request: NextRequest) => {
	const path = resolveRequestPath(request, {
		pathHeaderName: "x-accept-md-path",
		queryParamName: "path",
		handlerPath: HANDLER_PATH,
	});

	if (isPathExcluded(path, EXCLUDED_PATH_PREFIXES)) {
		return NextResponse.json({ error: "Not found" }, { status: 404 });
	}

	const config = loadConfig(process.cwd());

	const headers = new Headers(request.headers);
	headers.delete("accept");

	try {
		const markdown = await getMarkdownForPath({
			pathname: path,
			baseUrl: config.baseUrl ?? getBaseURLFromRequest(request, 3000).origin,
			config,
			cache: config.cache !== false ? cache : undefined,
			headers,
		});
		return new NextResponse(markdown, {
			headers: {
				"Content-Type": "text/markdown; charset=utf-8",
				"Cache-Control": config.cache ? "public, s-maxage=60, stale-while-revalidate" : "no-store",
			},
		});
	} catch (err) {
		let statusCode: number | null = null;

		if (err instanceof Error) {
			const statusMatch = err.message.match(/Failed to fetch page:\s*(\d{3})/);

			if (statusMatch) {
				const parsedStatusCode = Number.parseInt(statusMatch[1], 10);

				if (Number.isFinite(parsedStatusCode) && parsedStatusCode >= 400 && parsedStatusCode <= 599) {
					statusCode = parsedStatusCode;
				}
			}
		}

		if (statusCode === 404) {
			return new NextResponse(NOT_FOUND_MARKDOWN, {
				status: 404,
				headers: {
					"Content-Type": "text/markdown; charset=utf-8",
					"Cache-Control": "no-store",
				},
			});
		}

		return NextResponse.json(
			{ error: err instanceof Error ? err.message : "Markdown generation failed" },
			{ status: 500 }
		);
	}
});
