name: Check PR title

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
            - reopened

permissions:
    pull-requests: read

jobs:
    main:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              with:
                  configuration-path: .github/check-pr-title.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
